# Makefile for overlay_v4l2 driver for APE5R

ape5r_v4l2-objs :=  ape5r_overlay.o  ape5r_v4l2_disp.o ape5r_videobuf-mfi.o
ape5r_v4l2-objs +=  ape5r_entry.o

obj-$(CONFIG_VIDEO_APE5R_V4L2) += ape5r_v4l2.o

